name: Deploy App

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 3.228.25.62
        username: ec2-user
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ec2-user

          if [ ! -d "AWS-DevOps-agent" ]; then
            git clone https://github.com/dhruvdxb/AWS-DevOps-agent.git
          else
            cd AWS-DevOps-agent && git pull
          fi

          cd AWS-DevOps-agent

          sudo mkdir -p /var/www/html
          sudo cp index.html /var/www/html/index.html

          sudo yum install -y httpd
          sudo systemctl start httpd
          sudo systemctl enable httpd
